### PR TITLE
Added ability to handle multiple channels to greet on

### PR DESCRIPTION
**Pull request by patcon**
This will allow the bot to also work when entering `#bot-testing` channel, and therefore no need to create join/leave spam when testing changes :)

### CODE REVIEW

**Review by sonalranjit — CHANGES_REQUESTED** [review]
It would be more preferable to have different messages for different channels.

**Comment by patcon** [comment]
That's a great idea, but is that not another feature request?( this is for testing without entering/leaving a well-used channel -- which is _really_ noisy on mobile where the join/leaves aren't collapsed.)

Can we merge this for now, and we'll have https://github.com/CivicTechTO/slack-greeting-bot/issues/4 to track that?

**Review by sonalranjit — APPROVED** [review]

**Comment by sonalranjit** [comment]
sure that works for now

**Comment by sonalranjit** [comment]
This is live on the `bot-testing` channel and `organizing-open` @patcon

**Pull request merged**
